In [1]:
import tensorflow as tf
import numpy as np

定义训练时数据的batch大小

In [2]:
batch_size = 8

定义神经网络的参数

In [3]:
w1 = tf.Variable(tf.random_normal([2,3],stddev=1,seed=1))
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

In [4]:
x = tf.placeholder(tf.float32,shape=(None,2),name="x-input")
y_ = tf.placeholder(tf.float32,shape=(None,1),name="y-input")

In [5]:
a=tf.matmul(x,w1)
y=tf.matmul(a,w2)

定义损失函数和逆传播过程

In [6]:
cross_entropy=-tf.reduce_mean(\
                             y_*tf.log(tf.clip_by_value(1-y,1e-10,1.0)))
train_step=tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

随机生成数据集

In [7]:
rdm=np.random.RandomState(1)
dataset_size=128
X = rdm.rand(dataset_size,2)

定义标签，这里使x1+x2小于1时为正样本

In [8]:
Y=[[int(x1+x2<1)] for (x1,x2) in X]

In [13]:
Y

[[0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [1],
 [1],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [0],
 [1],
 [1],
 [1],
 [1],
 [1],
 [1],
 [0],
 [0],
 [0],
 [0],
 [0],
 [0],
 [1],
 [0],
 [0],
 [1],
 [0],
 [1],
 [0],
 [1],
 [0],
 [0]]

In [14]:
sess = tf.Session()

执行五千次
start和end规定了每个batch的大小，min是为了防止越界

In [25]:
with sess.as_default():
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    print(sess.run(w1))
    print(sess.run(w2))
    
    STEP=5000
    for i in range(STEP):
        start = (i*batch_size)%dataset_size
        end = min(start+batch_size,dataset_size)
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        if i%1000 == 0:
            total_cross_entropy = sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print("%d %e" %(i,total_cross_entropy))
    print(sess.run(w1))
    print(sess.run(w2))

[[ 1.05909669 -3.19847298  0.96108931]
 [-1.42169988 -0.07270738  0.28692925]]
[[-0.26764613]
 [ 0.72699791]
 [ 0.4133319 ]]
0 8.013457e+00
1000 5.623839e+00
2000 4.316242e+00
3000 4.237823e+00
4000 2.211766e+00
[[ 0.54248387 -2.79331589  1.4785614 ]
 [-1.8538307   0.23800059  0.71684015]]
[[-0.58162922]
 [ 0.27896062]
 [ 0.90702939]]


# 神经网络的训练包含三个步骤
1.定义神经网络的结构和前向传播的结果
2.定义损失函数以及选择反向传播优化的算法
3.生成会话session，并且在训练数据上反复运行反向传播优化算法