In [1]:
import tensorflow as tf

In [2]:
v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [6]:
with tf.Session() as sess:
    
    v=tf.constant([[1.0,2.0,3.0],[4.0,5.0,6.0]])
    print(tf.reduce_mean(v).eval())
    

3.5
[False  True False  True]
[ 3.  2.  5.  4.]


# 自定义损失函数,选择每列最大的一项

In [7]:
with tf.Session() as sess1:
    v1 = tf.constant([1.0,2.0,3.0,4.0])
    v2 = tf.constant([3.0,1.0,5.0,3.0])
    print(tf.greater(v1,v2).eval())
    print(tf.where(tf.greater(v1,v2),v1,v2).eval())
    


[False  True False  True]
[ 3.  2.  5.  4.]


# 对于自定义损失函数的应用

In [28]:
import numpy as np
batch_size = 8
x = tf.placeholder(tf.float32,shape=(None,2),name='x-input')
y_ = tf.placeholder(tf.float32,shape=(None,1),name='y-input')

In [29]:
w1 = tf.Variable(tf.random_normal([2,1],stddev=1,seed=1))
y = tf.matmul(x,w1)

# 定义多预测和少预测每个商品造成的损失

In [30]:
lose_less=10
lose_more=1

# 定义损失函数和优化算法

In [44]:
loss = tf.reduce_sum(tf.where(tf.greater(y,y_),lose_more*(y-y_),lose_less*(y_-y)))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

In [45]:
rdm = np.random.RandomState(5)
dataset_size=128
X = rdm.rand(dataset_size,2)

# rdm.rand()会产生0～1的随机数来生成噪音，而且噪音一般在-0.05～0.05之间

In [48]:
Y = [[x1+x2+rdm.rand()/10-0.05] for (x1,x2) in X]

# 此处因为若多预测会使损失总数变少，所以x1和x2前面的系数会大于0

In [50]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 100000
    for i in range(STEPS):
        start = (i*batch_size)%dataset_size
        end = min(start+batch_size,dataset_size)
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
    print(sess.run(w1))

[[ 1.00031078]
 [ 1.00049496]]
